<a href="https://colab.research.google.com/github/HariChandana-2305/AIML-2024-Assignments/blob/main/2203A52019_Lab_05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

# Read the dataset
data = pd.read_csv("housing.csv")

# a) Describe the data
data_description = data.describe()
print("Data Description:")
print(data_description)

# b) Data type and shape of each column
data_info = data.info()
print("\nData Types and Shape of Each Column:")
print(data_info)

# c) Find null values and fill them
null_values = data.isnull().sum()
print("\nNull Values:")
print(null_values)
# Filling null values with mean of each column
data_filled = data.fillna(data.mean())
print("\nData with Null Values Filled:")
print(data_filled)

Data Description:
          longitude      latitude  housing_median_age   total_rooms  \
count  20640.000000  20640.000000        20640.000000  20640.000000
mean    -119.569704     35.631861           28.639486   2635.763081
std        2.003532      2.135952           12.585558   2181.615252
min     -124.350000     32.540000            1.000000      2.000000
25%     -121.800000     33.930000           18.000000   1447.750000
50%     -118.490000     34.260000           29.000000   2127.000000
75%     -118.010000     37.710000           37.000000   3148.000000
max     -114.310000     41.950000           52.000000  39320.000000

       total_bedrooms    population    households  median_income  \
count    20433.000000  20640.000000  20640.000000   20640.000000
mean       537.870553   1425.476744    499.539680       3.870671
std        421.385070   1132.462122    382.329753       1.899822
min          1.000000      3.000000      1.000000       0.499900
25%        296.000000    787.000000    280.000000       2.563400
50%        435.000000   1166.000000    409.000000       3.534800
75%        647.000000   1725.000000    605.000000       4.743250
max       6445.000000  35682.000000   6082.000000      15.000100

       median_house_value
count        20640.000000
mean        206855.816909
std         115395.615874
min          14999.000000
25%         119600.000000
50%         179700.000000
75%         264725.000000
max         500001.000000
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object
dtypes: float64(9), object(1)
memory usage: 1.6+ MB

Data Types and Shape of Each Column:
None

Null Values:
longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

Data with Null Values Filled:
       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0
1        -122.22     37.86                21.0       7099.0          1106.0
2        -122.24     37.85                52.0       1467.0           190.0
3        -122.25     37.85                52.0       1274.0           235.0
4        -122.25     37.85                52.0       1627.0           280.0
...          ...       ...                 ...          ...             ...
20635    -121.09     39.48                25.0       1665.0           374.0
20636    -121.21     39.49                18.0        697.0           150.0
20637    -121.22     39.43                17.0       2254.0           485.0
20638    -121.32     39.43                18.0       1860.0           409.0
20639    -121.24     39.37                16.0       2785.0           616.0

       population  households  median_income  median_house_value  \
0           322.0       126.0         8.3252            452600.0
1          2401.0      1138.0         8.3014            358500.0
2           496.0       177.0         7.2574            352100.0
3           558.0       219.0         5.6431            341300.0
4           565.0       259.0         3.8462            342200.0
...           ...         ...            ...                 ...
20635       845.0       330.0         1.5603             78100.0
20636       356.0       114.0         2.5568             77100.0
20637      1007.0       433.0         1.7000             92300.0
20638       741.0       349.0         1.8672             84700.0
20639      1387.0       530.0         2.3886             89400.0

      ocean_proximity
0            NEAR BAY
1            NEAR BAY
2            NEAR BAY
3            NEAR BAY
4            NEAR BAY
...               ...
20635          INLAND
20636          INLAND
20637          INLAND
20638          INLAND
20639          INLAND

[20640 rows x 10 columns]

<ipython-input-1-6e516124f679>:21: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  data_filled = data.fillna(data.mean())

In [2]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

# Load the data into a DataFrame
data = pd.read_csv('/content/housing.csv')

# Print the first few rows to get a glimpse of the data
print(data.head())

# Identify features (predictors) and target variable (response)
features = ['longitude', 'latitude', 'housing_median_age', 'total_rooms',
            'total_bedrooms', 'population', 'households', 'median_income']
target = 'median_house_value'

# Normalize the features (excluding the target variable)
scaler = MinMaxScaler()
data_scaled = scaler.fit_transform(data[features])
data_normalized = pd.DataFrame(data_scaled, columns=features)

# Combine the normalized features with the original target variable
data_normalized = pd.concat([data_normalized, data[target]], axis=1)

# Print the first few rows to verify normalization
print(data_normalized.head())

# Split the normalized data into training and testing sets (default test_size=0.25)
X_train, X_test, y_train, y_test = train_test_split(
    data_normalized[features],
    data_normalized[target],
    test_size=0.25,
    random_state=42
)

# Create a linear regression model
model = LinearRegression()

# Train the model using the training data
model.fit(X_train, y_train)

# Print the coefficients of the model
print("Model coefficients:", model.coef_)

# Make predictions on the test data
predictions = model.predict(X_train)

# Print the mean squared error of the predictions
print("Mean squared error:", ((y_train - predictions) ** 2).mean())

   longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0
1    -122.22     37.86                21.0       7099.0          1106.0
2    -122.24     37.85                52.0       1467.0           190.0
3    -122.25     37.85                52.0       1274.0           235.0
4    -122.25     37.85                52.0       1627.0           280.0

   population  households  median_income  median_house_value ocean_proximity
0       322.0       126.0         8.3252            452600.0        NEAR BAY
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY
2       496.0       177.0         7.2574            352100.0        NEAR BAY
3       558.0       219.0         5.6431            341300.0        NEAR BAY
4       565.0       259.0         3.8462            342200.0        NEAR BAY
   longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0   0.211155  0.567481            0.784314     0.022331        0.019863
1   0.212151  0.565356            0.392157     0.180503        0.171477
2   0.210159  0.564293            1.000000     0.037260        0.029330
3   0.209163  0.564293            1.000000     0.032352        0.036313
4   0.209163  0.564293            1.000000     0.041330        0.043296

   population  households  median_income  median_house_value
0    0.008941    0.020556       0.539668            452600.0
1    0.067210    0.186976       0.538027            358500.0
2    0.013818    0.028943       0.466028            352100.0
3    0.015555    0.035849       0.354699            341300.0
4    0.015752    0.042427       0.230776            342200.0
Model coefficients: [ -429370.97481566  -399919.0310314     59791.74266074  -320592.29154044
   773448.14254833 -1364239.82104097   252301.09024554   585367.33104932]
Mean squared error: 4837165112.001602